### ISSUE TITLE
Build rootfs without physical device

### ISSUE THREAD

**Issue by GrabbenD** [wick3dr0se/archstrap#1]
Is it possible to install to a directory without mounting any physical devices inside of it? This would be useful for building rootfs on a workstation computer before installing the rootfs to a physical device like a embedded system.

Here's what I've tried:
```console
# git clone https://github.com/wick3dr0se/archstrap; cd "${_%/*}"

# mkdir -p /mnt/arch

# chmod +x archstrap

# ./archstrap /mnt/arch
!: Downloading bootstrap tarball & signature..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  179M  100  179M    0     0  37.9M      0  0:00:04  0:00:04 --:--:-- 40.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0   1305      0 --:--:-- --:--:-- --:--:--  1317
!: Target downloaded. Verifying tarball GPG signature..
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: Signature made Tue Aug  1 12:20:05 2023 UTC
gpg:                using EDDSA key 3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C
gpg:                issuer "pierre@archlinux.org"
gpg: Can't check signature: No public key
x: Bad signature. GPG key must be received

# gpg --receive-key 3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 76A5EF9054449A5C: public key "Pierre Schmitz <pierre@archlinux.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

# ./archstrap /mnt/arch
!: Downloading bootstrap tarball & signature..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  179M  100  179M    0     0  42.6M      0  0:00:04  0:00:04 --:--:-- 43.9M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0   1402      0 --:--:-- --:--:-- --:--:--  1410
!: Target downloaded. Verifying tarball GPG signature..
gpg: Signature made Tue Aug  1 12:20:05 2023 UTC
gpg:                using EDDSA key 3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C
gpg:                issuer "pierre@archlinux.org"
gpg: Good signature from "Pierre Schmitz <pierre@archlinux.org>" [unknown]
gpg:                 aka "Pierre Schmitz <pierre@archlinux.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 3E80 CA1A 8B89 F69C BA57  D98A 76A5 EF90 5444 9A5C
>: Signature verified
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
>: Bootstrapped tarball unpacked to /mnt/arch/root.x86_64
>: Created necessary chroot system files
mount: /mnt/arch/root.x86_64: permission denied.
       dmesg(1) may have more information after failed mount system call.

# whoami
root
```

**Comment by wick3dr0se** [comment]
As far as I know, it's impossible without bind mounting to a directory. I will do some research and see if I can figure out another options or if that is in fact possible. I do see you are not running it as root which is an issue. To mount and several other things, it must be ran as root. Is `archstrap` not throwing an error when you don't execute with superuser or did you remove that check?

**Comment by GrabbenD** [comment]
> I do see you are not running it as root which is an issue

I'm not using `sudo` since I'm in the `root` account, there's no user accounts in this setup

>  Is archstrap not throwing an error when you don't execute with superuser or did you remove that check?

I'm running all of these commands inside a (rootful) Podman container:
```
sudo podman run -it archlinux /bin/bash
```

> As far as I know, it's impossible without bind mounting to a directory

For reference, `/mnt/archlinux` is just a directory inside the Podman container. I haven't mounted any storage devices as I'm just trying to build a rootfs image

> I will do some research and see if I can figure out another options or if that is in fact possible

Thanks!

**Comment by wick3dr0se** [comment]
> For reference, /mnt/archlinux is just a directory inside the Podman container. I haven't mounted any storage devices as I'm just trying to build a rootfs image

I see now! I took your first request wrong but that's actually a genuis idea! If you want to just create the rootfs without mounting I could implement a flag that makes the script stop after rootfs creation. Currently you could go through with the entire script, `exit` the chroot and then `umount` the mounted directory. The rootfs will remain intact wherever you were mounted at. Actually it has to be manually deleted or it always persist; I did it this way to make it able to be `chroot`ed into at any time

You could then move it anywhere you want and use the builtin `arch-chroot` to chroot back in. `<location>/rootfs.x86_64/bin/arch-chroot <location>`

**Comment by GrabbenD** [comment]
The flag is a great idea, sounds like a good way of going about it 👍🏼

**Comment by wick3dr0se** [comment]
> The flag is a great idea, sounds like a good way of going about it 👍🏼

@GrabbenD, took me awhile to get around to it but I implemented a --buildfs flag just now. It also will keep the tarball in /tmp to keep from downloading over & over; Signature gets downloaded everytime. Now you can also specify the name of the root filesystem output by archstrap as the second argument. The flag must be the third and last argument. Didn't implement some arg parses (just seems unecessary currently)
