### ISSUE TITLE
'tar: can't create symlink 'root.x86_64/bin' to 'usr/bin': Operation not permitted' in alpine linux

### ISSUE THREAD

**Issue by tony1016** [wick3dr0se/archstrap#5]
Just execute `sudo bash archstrap /opt/service` but got

```
tar: can't create symlink 'root.x86_64/bin' to 'usr/bin
```

**Comment by wick3dr0se** [comment]
I believe Alpine uses BusyBox and that's likely the culprit. BB tar implementation is probably much different than GNU tar. But besides that you will probably hit other obstacles. This script heavily relies on coreutils. I will have to make a distinction for this as I don't plan to support BusyBox unless someone wants to take up that end of it and it's rather simple

**Comment by tony1016** [comment]
fine

wick3dr0se ***@***.***> 于2024年4月2日周二 07:12写道：
